import { Language } from "@/lib/types";

export const CHECKER_SOURCE_TEMPLATES: Record<Language, string> = {
  cpp: [
    "#include <bits/stdc++.h>",
    "using namespace std;",
    "",
    "string read_all(const string& path) {",
    "  ifstream ifs(path);",
    "  return string((istreambuf_iterator<char>(ifs)), istreambuf_iterator<char>());",
    "}",
    "",
    "int main(int argc, char** argv) {",
    "  if (argc != 4) {",
    '    cerr << "invalid arguments";',
    "    return 2;",
    "  }",
    "",
    "  const string input_path = argv[1];",
    "  const string answer_path = argv[2];",
    "  const string output_path = argv[3];",
    "",
    "  const string expected = read_all(answer_path);",
    "  const string actual = read_all(output_path);",
    "",
    "  if (expected == actual) {",
    '    cout << "Accepted";',
    "    return 0;",
    "  }",
    "",
    '  cout << "Wrong answer";',
    "  return 1;",
    "}",
  ].join("\n"),
  python: [
    "import sys",
    "",
    "",
    "def read_all(path: str) -> str:",
    '    with open(path, "r", encoding="utf-8") as f:',
    "        return f.read()",
    "",
    "",
    "def main() -> int:",
    "    if len(sys.argv) != 4:",
    '        print("invalid arguments", file=sys.stderr)',
    "        return 2",
    "",
    "    input_path = sys.argv[1]",
    "    answer_path = sys.argv[2]",
    "    output_path = sys.argv[3]",
    "",
    "    expected = read_all(answer_path)",
    "    actual = read_all(output_path)",
    "",
    "    if expected == actual:",
    '        print("Accepted")',
    "        return 0",
    "",
    '    print("Wrong answer")',
    "    return 1",
    "",
    "",
    "if __name__ == '__main__':",
    "    raise SystemExit(main())",
  ].join("\n"),
  java: [
    "import java.io.IOException;",
    "import java.nio.file.Files;",
    "import java.nio.file.Path;",
    "",
    "public class Main {",
    "  static String readAll(String path) throws IOException {",
    "    return Files.readString(Path.of(path));",
    "  }",
    "",
    "  public static void main(String[] args) throws Exception {",
    "    if (args.length != 3) {",
    '      System.err.println("invalid arguments");',
    "      System.exit(2);",
    "    }",
    "",
    "    String inputPath = args[0];",
    "    String answerPath = args[1];",
    "    String outputPath = args[2];",
    "",
    "    String expected = readAll(answerPath);",
    "    String actual = readAll(outputPath);",
    "",
    "    if (expected.equals(actual)) {",
    '      System.out.println("Accepted");',
    "      System.exit(0);",
    "    }",
    "",
    '    System.out.println("Wrong answer");',
    "    System.exit(1);",
    "  }",
    "}",
  ].join("\n"),
  javascript: [
    "'use strict';",
    "",
    "const fs = require('fs');",
    "",
    "function readAll(path) {",
    "  return fs.readFileSync(path, 'utf8');",
    "}",
    "",
    "function main() {",
    "  if (process.argv.length !== 5) {",
    "    console.error('invalid arguments');",
    "    process.exit(2);",
    "  }",
    "",
    "  const inputPath = process.argv[2];",
    "  const answerPath = process.argv[3];",
    "  const outputPath = process.argv[4];",
    "",
    "  const expected = readAll(answerPath);",
    "  const actual = readAll(outputPath);",
    "",
    "  if (expected === actual) {",
    "    console.log('Accepted');",
    "    process.exit(0);",
    "  }",
    "",
    "  console.log('Wrong answer');",
    "  process.exit(1);",
    "}",
    "",
    "main();",
  ].join("\n"),
};

export function isDefaultCheckerSourceTemplate(code: string): boolean {
  return Object.values(CHECKER_SOURCE_TEMPLATES).includes(code);
}
